steps:
  # Build the Angular app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: '.'
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build', '--', '--configuration=production']
    dir: '.'
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--port=80'
      - '--allow-unauthenticated'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--startup-cpu-boost'
options:
  logging: CLOUD_LOGGING_ONLY
images: ['gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']
