steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/driverrelay-frontend/driverrelay-frontend:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/driverrelay-frontend/driverrelay-frontend:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'driverrelay-frontend'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/driverrelay-frontend/driverrelay-frontend:$COMMIT_SHA'
      - '--no-allow-unauthenticated'
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/driverrelay-frontend/driverrelay-frontend:$COMMIT_SHA'
